### ISSUE TITLE
Would you upload the code?

### ISSUE THREAD

**Issue by ninali1009** [AhmedElkelesh/Genetic-Algorithm-based-Polar-Code-Construction#1]
I read your paper and interested it.
The paper is provided a link of the code.
However, there is no code.
Would you upload the code?
Thank you !
best regard.

**Comment by Alan-ic** [comment]
Hi, I have the same problem? If convenient, could you please upload the "code/modulation/channel/decoder"? Thanks. 

Best Regard!
